
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN H20 [get_ports {blue[0]}]
set_property PACKAGE_PIN G20 [get_ports {blue[1]}]
set_property PACKAGE_PIN K21 [get_ports {blue[2]}]
set_property PACKAGE_PIN K22 [get_ports {blue[3]}]
set_property PACKAGE_PIN H17 [get_ports {green[0]}]
set_property PACKAGE_PIN H18 [get_ports {green[1]}]
set_property PACKAGE_PIN J22 [get_ports {green[2]}]
set_property PACKAGE_PIN H22 [get_ports {green[3]}]
set_property PACKAGE_PIN G17 [get_ports {red[0]}]
set_property PACKAGE_PIN G18 [get_ports {red[1]}]
set_property PACKAGE_PIN J15 [get_ports {red[2]}]
set_property PACKAGE_PIN H15 [get_ports {red[3]}]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN M21 [get_ports hs]
set_property PACKAGE_PIN Y9 [get_ports rst]
set_property PACKAGE_PIN L21 [get_ports vs]
set_property PACKAGE_PIN Y19 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports choose]

set_property IOSTANDARD LVCMOS33 [get_ports {functional[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {functional[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {functional[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {functional[3]}]
set_property PACKAGE_PIN W4 [get_ports {functional[0]}]
set_property PACKAGE_PIN R4 [get_ports {functional[1]}]
set_property PACKAGE_PIN T4 [get_ports {functional[2]}]
set_property PACKAGE_PIN T5 [get_ports {functional[3]}]
set_property PACKAGE_PIN U5 [get_ports choose]


set_property IOSTANDARD LVCMOS33 [get_ports refresh]
set_property PACKAGE_PIN  W9 [get_ports refresh]

set_property IOSTANDARD LVCMOS33 [get_ports active]
set_property PACKAGE_PIN K17 [get_ports active]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]

set_property PACKAGE_PIN F15 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN E17 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[3]}]

set_property PACKAGE_PIN P1 [get_ports {button[0]}]
set_property PACKAGE_PIN R1 [get_ports {button[1]}]
set_property PACKAGE_PIN P5 [get_ports {button[2]}]
set_property PACKAGE_PIN P2 [get_ports {button[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]

set_property PACKAGE_PIN C19 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN D19 [get_ports {led[2]}]
set_property PACKAGE_PIN E18 [get_ports {led[4]}]
set_property PACKAGE_PIN A18 [get_ports {led[7]}]
set_property PACKAGE_PIN A20 [get_ports {led[6]}]
set_property PACKAGE_PIN B20 [get_ports {led[5]}]
set_property PACKAGE_PIN F18 [get_ports {led[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN P4 [get_ports rst_n]