# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/con1.xdc

# IP: ip/blk_mem_gen_0_1_1/blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_1 || ORIG_REF_NAME==blk_mem_gen_0_1} -quiet] -quiet
